### ISSUE TITLE
AttributeError: 'EdgeFollowEnv' object has no attribute '_pb'

### ISSUE THREAD

**Issue by ZJU-PLP** [ac-93/tactile_gym#12]
@ac-93 

I meet the error when to run script "python examples/demo_trained_agent.py -env='env_name' -obs='obs_type' -algo='algo_name'
". The models have downloaded and placed in the path of "tactile_gym/examples/enjoy".
 Would you mind sharing the method to solve this problem?
![image](https://user-images.githubusercontent.com/32757213/229275034-b7b63b99-5a9e-462b-b4b0-64a8649531f6.png)
![image](https://user-images.githubusercontent.com/32757213/229275038-d2646041-b207-471f-8be2-5e39ec91e353.png)

**Comment by yijionglin** [comment]
Hi @ZJU-PLP ,

It looks like a problem caused by some wrong 'arm_type". Could you please let us know what you have put in it?

Best,
Yijiong

**Comment by ZJU-PLP** [comment]
> Hi @ZJU-PLP ,
> 
> It looks like a problem caused by some wrong 'arm_type". Could you please let us know what you have put in it?
> 
> Best, Yijiong

I have solved this problem. Thanks for your reply.
